### ISSUE TITLE
[FAQ] 运行时屏幕闪烁一次后进度条不消失，无法进入主界面

### ISSUE THREAD

**Issue by updateing** [updateing/k3screenctrl#1]
自行编译 LEDE 时选择此包集成到系统，但开机后屏幕只会闪烁一次，之后继续走进度条而不能进入信息显示界面，按键也无法操作。

**Comment by updateing** [comment]
注意查看系统日志 (或者用 `-f` 启动程序以便同时打印到 stderr) 会有如下信息：

```
Unable to access memory: No such file or directory
```

考虑到 `No such file or directory` 是通用的提示，故搜索 `Unable to access memory` 可搜索到此信息来自于[这里](https://github.com/updateing/k3screenctrl/blob/master/src/mem_util.c#L23)

具体解释如下：

1. 第二串口的 pin 默认用于 GPIO
2. 目前 DT 中尚未定义第二串口相关的 pin mux，所以需要手动修改相关寄存器将相应 pin 设置为串口
3. LEDE 默认不提供用于原始内存访问的 `/dev/mem` 设备，而从用户空间修改寄存器时需要直接访问物理内存

因此在 LEDE 中打开 `/dev/mem` 支持即可，具体设置在 Global build configuration 中。打开后需重新编译刷写镜像。

**Comment by kotori2** [comment]
建议检查WiFi名字有没有什么奇怪的字符
