### ISSUE TITLE
大神，这个k3screenctrl

### ISSUE THREAD

**Issue by refugeer** [updateing/k3screenctrl#6]
请问这个 k3screenctrl 是 某讯泄露出来的么。

有没有可能弄到屏幕单片机的SDK呀。

如果不是的话，大神真的辛苦，这个frame是你一帧一帧测试的么，或者有什么相应的解决思路。。。
请不吝赐教下

感谢。

FRAME_HEADER | PAYLOAD_HEADER | PAYLOAD_TYPE | PAYLOAD | FRAME_TRAILER

**Comment by updateing** [comment]
逆向出来的…… 它自己也有日志可以分析格式。

单片机类型可以直接看芯片，自己要写程序也很容易，但没有调试端口就不方便了。

要是泄露的话，功能不可能只有这么点 :-)

**Comment by refugeer** [comment]
原来是逆向出来的。真不容易。O(∩_∩)O~~

感谢回复，谢谢~
