### ISSUE TITLE
phicomm k3屏幕无法待机

### ISSUE THREAD

**Issue by csrbzhb** [updateing/k3screenctrl#7]
http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=251361&extra=page%3D1%26filter%3Dtypeid%26typeid%3D15
这是网有移植的驱动，但是在斐讯k3机器上无法待机。希望改进屏幕的待机功能。
ps:正常mipi屏幕待机只有下 10 28命令，当然还可能做复位及关闭屏5V电压。

**Comment by updateing** [comment]
由于此贴并未使用本项目，我也不擅长 binary hacking，恕无法提供帮助。

此外 K3 这块屏幕的 Host 端控制与 MIPI 规范没有关系。Host 这边只是发送类文本信息到控制屏幕的 MCU 上，由 MCU 控制显示，Host 端没有办法直接控制屏幕。
